name: bars
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4

  intl: ^0.18.1
  floor: ^1.4.2
  cached_network_image: ^3.3.0

  retrofit: ^4.0.1
  flutter_hooks: ^0.20.1

  yandex_mapkit: ^3.2.0
  geolocator: ^9.0.2
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  fonts:
    - family: Finlandica
      fonts:
        - asset: assets/fonts/finlandica/Finlandica-Regular.ttf
        - asset: assets/fonts/finlandica/Finlandica-Bold.ttf
          weight: 700
        - asset: assets/fonts/finlandica/Finlandica-Italic.ttf
          style: italic
    - family: Soledago
      fonts:
        - asset: assets/fonts/soledago/Soledago.ttf
          weight: 700
