name: bars
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4

  intl: ^0.18.1
  floor: ^1.4.2
  cached_network_image: ^3.3.0

  retrofit: ^4.0.1
  flutter_hooks: ^0.20.3

  yandex_mapkit: ^3.2.0
  geolocator: ^9.0.2
  dio: ^5.3.3
  vexana: ^3.5.4
  after_layout: ^1.2.0
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/icons/placemark.png
    - assets/icons/placemark_pin.png
    - assets/test/534-1000x830.jpg

  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica/helvetica_regular.otf
        - asset: assets/fonts/helvetica/helvetica_bold.otf
          weight: 700
        - asset: assets/fonts/helvetica/helvetica_oblique.otf
          style: italic
    - family: Playfair_Display
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Italic.ttf
          style: italic
    - family: AppleColorEmoji
      fonts:
        - asset: assets/fonts/apple_color_emoji/AppleColorEmoji.ttf
          weight: 700